import Foundation

/// A static, searchable emoji catalog for the Emojis tab. Data is embedded so
/// there are no external files to ship; it is small enough to fit in memory.
/// Searching matches name and keywords, case-insensitive, accent-insensitive.
public struct EmojiEntry: Identifiable, Hashable, Sendable {
    public let id: String          // the glyph itself is unique
    public let glyph: String
    public let name: String
    public let keywords: [String]
    public let category: EmojiCategory

    public init(glyph: String, name: String, keywords: [String], category: EmojiCategory) {
        self.id = glyph
        self.glyph = glyph
        self.name = name
        self.keywords = keywords
        self.category = category
    }
}

public enum EmojiCategory: String, CaseIterable, Sendable {
    case smileys = "Smileys & People"
    case animals = "Animals & Nature"
    case food = "Food & Drink"
    case activities = "Activities"
    case travel = "Travel & Places"
    case objects = "Objects"
    case symbols = "Symbols"
    case flags = "Flags"
}

public enum EmojiCatalog {
    /// Full catalog. Curated to cover common usage without bloating the
    /// binary; categories match the order in the Emoji tab sections.
    public static let entries: [EmojiEntry] = [
        // Smileys & People
        .init(glyph: "😀", name: "Grinning Face", keywords: ["happy", "smile", "joy"], category: .smileys),
        .init(glyph: "😃", name: "Grinning Face with Big Eyes", keywords: ["happy", "joy", "smile"], category: .smileys),
        .init(glyph: "😄", name: "Grinning Face with Smiling Eyes", keywords: ["happy", "joy", "laugh"], category: .smileys),
        .init(glyph: "😁", name: "Beaming Face with Smiling Eyes", keywords: ["happy", "grin"], category: .smileys),
        .init(glyph: "😆", name: "Grinning Squinting Face", keywords: ["laugh", "happy"], category: .smileys),
        .init(glyph: "😅", name: "Grinning Face with Sweat", keywords: ["relief", "phew"], category: .smileys),
        .init(glyph: "🤣", name: "Rolling on the Floor Laughing", keywords: ["rofl", "lol", "laugh"], category: .smileys),
        .init(glyph: "😂", name: "Face with Tears of Joy", keywords: ["laugh", "cry", "joy"], category: .smileys),
        .init(glyph: "🙂", name: "Slightly Smiling Face", keywords: ["smile"], category: .smileys),
        .init(glyph: "🙃", name: "Upside-Down Face", keywords: ["sarcasm", "irony"], category: .smileys),
        .init(glyph: "😉", name: "Winking Face", keywords: ["wink", "flirt"], category: .smileys),
        .init(glyph: "😊", name: "Smiling Face with Smiling Eyes", keywords: ["happy", "blush"], category: .smileys),
        .init(glyph: "😇", name: "Smiling Face with Halo", keywords: ["angel", "innocent"], category: .smileys),
        .init(glyph: "🥰", name: "Smiling Face with Hearts", keywords: ["love", "adore"], category: .smileys),
        .init(glyph: "😍", name: "Smiling Face with Heart-Eyes", keywords: ["love", "heart"], category: .smileys),
        .init(glyph: "🤩", name: "Star-Struck", keywords: ["wow", "cool", "star"], category: .smileys),
        .init(glyph: "😘", name: "Face Blowing a Kiss", keywords: ["kiss", "love"], category: .smileys),
        .init(glyph: "😗", name: "Kissing Face", keywords: ["kiss"], category: .smileys),
        .init(glyph: "😚", name: "Kissing Face with Closed Eyes", keywords: ["kiss"], category: .smileys),
        .init(glyph: "😙", name: "Kissing Face with Smiling Eyes", keywords: ["kiss"], category: .smileys),
        .init(glyph: "😋", name: "Face Savoring Food", keywords: ["yum", "tongue"], category: .smileys),
        .init(glyph: "😛", name: "Face with Tongue", keywords: ["tongue", "raspberry"], category: .smileys),
        .init(glyph: "😜", name: "Winking Face with Tongue", keywords: ["wink", "tongue"], category: .smileys),
        .init(glyph: "🤪", name: "Zany Face", keywords: ["crazy", "goofy"], category: .smileys),
        .init(glyph: "🤨", name: "Face with Raised Eyebrow", keywords: ["skeptical", "suspicious"], category: .smileys),
        .init(glyph: "🧐", name: "Face with Monocle", keywords: ["stuffy", "wealthy"], category: .smileys),
        .init(glyph: "🤓", name: "Nerd Face", keywords: ["nerd", "geek"], category: .smileys),
        .init(glyph: "😎", name: "Smiling Face with Sunglasses", keywords: ["cool", "sunglasses"], category: .smileys),
        .init(glyph: "🥳", name: "Partying Face", keywords: ["party", "celebrate"], category: .smileys),
        .init(glyph: "😏", name: "Smirking Face", keywords: ["smirk"], category: .smileys),
        .init(glyph: "😒", name: "Unamused Face", keywords: ["meh", "unhappy"], category: .smileys),
        .init(glyph: "😞", name: "Disappointed Face", keywords: ["sad"], category: .smileys),
        .init(glyph: "😔", name: "Pensive Face", keywords: ["sad", "pensive"], category: .smileys),
        .init(glyph: "😟", name: "Worried Face", keywords: ["worried", "anxious"], category: .smileys),
        .init(glyph: "😕", name: "Confused Face", keywords: ["confused", "huh"], category: .smileys),
        .init(glyph: "🙁", name: "Slightly Frowning Face", keywords: ["sad"], category: .smileys),
        .init(glyph: "☹️", name: "Frowning Face", keywords: ["sad"], category: .smileys),
        .init(glyph: "😮", name: "Face with Open Mouth", keywords: ["surprise", "wow"], category: .smileys),
        .init(glyph: "😯", name: "Hushed Face", keywords: ["surprise", "quiet"], category: .smileys),
        .init(glyph: "😲", name: "Astonished Face", keywords: ["shock", "astonished"], category: .smileys),
        .init(glyph: "😳", name: "Flushed Face", keywords: ["blush", "embarrassed"], category: .smileys),
        .init(glyph: "🥺", name: "Pleading Face", keywords: ["beg", "pleading"], category: .smileys),
        .init(glyph: "😦", name: "Frowning Face with Open Mouth", keywords: ["aww"], category: .smileys),
        .init(glyph: "😧", name: "Anguished Face", keywords: ["anguished"], category: .smileys),
        .init(glyph: "😨", name: "Fearful Face", keywords: ["scared", "fear"], category: .smileys),
        .init(glyph: "😰", name: "Anxious Face with Sweat", keywords: ["anxious", "sweat"], category: .smileys),
        .init(glyph: "😥", name: "Sad but Relieved Face", keywords: ["sad", "relief"], category: .smileys),
        .init(glyph: "😢", name: "Crying Face", keywords: ["sad", "cry", "tear"], category: .smileys),
        .init(glyph: "😭", name: "Loudly Crying Face", keywords: ["cry", "sob", "sad"], category: .smileys),
        .init(glyph: "😱", name: "Face Screaming in Fear", keywords: ["scream", "fear"], category: .smileys),
        .init(glyph: "😖", name: "Confounded Face", keywords: ["confounded"], category: .smileys),
        .init(glyph: "😣", name: "Persevering Face", keywords: ["persevere"], category: .smileys),
        .init(glyph: "😞", name: "Disappointed Face", keywords: ["disappointed"], category: .smileys),
        .init(glyph: "😓", name: "Downcast Face with Sweat", keywords: ["sweat", "sad"], category: .smileys),
        .init(glyph: "😩", name: "Weary Face", keywords: ["weary", "tired"], category: .smileys),
        .init(glyph: "😫", name: "Tired Face", keywords: ["tired", "exhausted"], category: .smileys),
        .init(glyph: "🥱", name: "Yawning Face", keywords: ["yawn", "tired"], category: .smileys),
        .init(glyph: "😤", name: "Face with Steam from Nose", keywords: ["angry", "frustrated"], category: .smileys),
        .init(glyph: "😡", name: "Pouting Face", keywords: ["angry", "mad", "rage"], category: .smileys),
        .init(glyph: "😠", name: "Angry Face", keywords: ["angry", "mad"], category: .smileys),
        .init(glyph: "🤬", name: "Face with Symbols on Mouth", keywords: ["swearing", "cursing"], category: .smileys),
        .init(glyph: "😈", name: "Smiling Face with Horns", keywords: ["devil", "devil horns"], category: .smileys),
        .init(glyph: "👿", name: "Angry Face with Horns", keywords: ["devil", "imp"], category: .smileys),
        .init(glyph: "💀", name: "Skull", keywords: ["death", "skull", "dead"], category: .smileys),
        .init(glyph: "💩", name: "Pile of Poo", keywords: ["poop", "shit"], category: .smileys),
        .init(glyph: "🤡", name: "Clown Face", keywords: ["clown"], category: .smileys),
        .init(glyph: "👻", name: "Ghost", keywords: ["spooky", "halloween"], category: .smileys),
        .init(glyph: "👽", name: "Alien", keywords: ["alien", "ufo"], category: .smileys),
        .init(glyph: "🙌", name: "Raising Hands", keywords: ["celebrate", "praise"], category: .smileys),
        .init(glyph: "👏", name: "Clapping Hands", keywords: ["clap", "applause"], category: .smileys),
        .init(glyph: "👍", name: "Thumbs Up", keywords: ["yes", "good", "like"], category: .smileys),
        .init(glyph: "👎", name: "Thumbs Down", keywords: ["no", "bad", "dislike"], category: .smileys),
        .init(glyph: "👌", name: "OK Hand", keywords: ["ok", "okay"], category: .smileys),
        .init(glyph: "🤞", name: "Crossed Fingers", keywords: ["luck", "hope"], category: .smileys),
        .init(glyph: "✌️", name: "Victory Hand", keywords: ["peace", "victory"], category: .smileys),
        .init(glyph: "🤟", name: "Love-You Gesture", keywords: ["love", "rock"], category: .smileys),
        .init(glyph: "🤙", name: "Call Me Hand", keywords: ["call", "shaka"], category: .smileys),
        .init(glyph: "👈", name: "Backhand Index Pointing Left", keywords: ["point", "left"], category: .smileys),
        .init(glyph: "👉", name: "Backhand Index Pointing Right", keywords: ["point", "right"], category: .smileys),
        .init(glyph: "👆", name: "Backhand Index Pointing Up", keywords: ["point", "up"], category: .smileys),
        .init(glyph: "👇", name: "Backhand Index Pointing Down", keywords: ["point", "down"], category: .smileys),
        .init(glyph: "☝️", name: "Index Pointing Up", keywords: ["point", "up", "one"], category: .smileys),
        .init(glyph: "👋", name: "Waving Hand", keywords: ["wave", "hello", "bye"], category: .smileys),
        .init(glyph: "🤝", name: "Handshake", keywords: ["shake", "deal"], category: .smileys),
        .init(glyph: "🙏", name: "Folded Hands", keywords: ["pray", "thanks", "please"], category: .smileys),
        .init(glyph: "💪", name: "Flexed Biceps", keywords: ["muscle", "strong"], category: .smileys),
        .init(glyph: "👀", name: "Eyes", keywords: ["eyes", "look", "watch"], category: .smileys),
        .init(glyph: "🧠", name: "Brain", keywords: ["brain", "smart"], category: .smileys),
        .init(glyph: "❤️", name: "Red Heart", keywords: ["love", "heart"], category: .smileys),
        .init(glyph: "🧡", name: "Orange Heart", keywords: ["heart", "orange"], category: .smileys),
        .init(glyph: "💛", name: "Yellow Heart", keywords: ["heart", "yellow"], category: .smileys),
        .init(glyph: "💚", name: "Green Heart", keywords: ["heart", "green"], category: .smileys),
        .init(glyph: "💙", name: "Blue Heart", keywords: ["heart", "blue"], category: .smileys),
        .init(glyph: "💜", name: "Purple Heart", keywords: ["heart", "purple"], category: .smileys),
        .init(glyph: "🖤", name: "Black Heart", keywords: ["heart", "black"], category: .smileys),
        .init(glyph: "🤍", name: "White Heart", keywords: ["heart", "white"], category: .smileys),
        .init(glyph: "🤎", name: "Brown Heart", keywords: ["heart", "brown"], category: .smileys),
        .init(glyph: "💔", name: "Broken Heart", keywords: ["heart", "broken", "sad"], category: .smileys),
        .init(glyph: "💕", name: "Two Hearts", keywords: ["love", "hearts"], category: .smileys),
        .init(glyph: "💖", name: "Sparkling Heart", keywords: ["love", "sparkle"], category: .smileys),
        .init(glyph: "💯", name: "Hundred Points", keywords: ["100", "perfect", "score"], category: .smileys),
        .init(glyph: "💢", name: "Anger Symbol", keywords: ["anger", "angry"], category: .smileys),
        .init(glyph: "💥", name: "Collision", keywords: ["boom", "collision"], category: .smileys),
        .init(glyph: "💫", name: "Dizzy", keywords: ["dizzy", "star"], category: .smileys),
        .init(glyph: "💦", name: "Sweat Droplets", keywords: ["sweat", "water"], category: .smileys),
        .init(glyph: "💨", name: "Dashing Away", keywords: ["dash", "wind", "fast"], category: .smileys),
        .init(glyph: "🕳️", name: "Hole", keywords: ["hole"], category: .smileys),
        .init(glyph: "💣", name: "Bomb", keywords: ["bomb"], category: .smileys),
        .init(glyph: "💬", name: "Speech Balloon", keywords: ["speech", "chat", "talk"], category: .smileys),
        .init(glyph: "💭", name: "Thought Balloon", keywords: ["thought", "think"], category: .smileys),
        .init(glyph: "💤", name: "Zzz", keywords: ["sleep", "tired"], category: .smileys),

        // Animals & Nature
        .init(glyph: "🐶", name: "Dog Face", keywords: ["dog", "puppy", "pet"], category: .animals),
        .init(glyph: "🐱", name: "Cat Face", keywords: ["cat", "kitten", "pet"], category: .animals),
        .init(glyph: "🐭", name: "Mouse Face", keywords: ["mouse"], category: .animals),
        .init(glyph: "🐹", name: "Hamster", keywords: ["hamster", "pet"], category: .animals),
        .init(glyph: "🐰", name: "Rabbit Face", keywords: ["rabbit", "bunny"], category: .animals),
        .init(glyph: "🦊", name: "Fox", keywords: ["fox"], category: .animals),
        .init(glyph: "🐻", name: "Bear", keywords: ["bear"], category: .animals),
        .init(glyph: "🐼", name: "Panda", keywords: ["panda", "bear"], category: .animals),
        .init(glyph: "🐨", name: "Koala", keywords: ["koala"], category: .animals),
        .init(glyph: "🐯", name: "Tiger Face", keywords: ["tiger"], category: .animals),
        .init(glyph: "🦁", name: "Lion", keywords: ["lion"], category: .animals),
        .init(glyph: "🐮", name: "Cow Face", keywords: ["cow"], category: .animals),
        .init(glyph: "🐷", name: "Pig Face", keywords: ["pig"], category: .animals),
        .init(glyph: "🐸", name: "Frog", keywords: ["frog"], category: .animals),
        .init(glyph: "🐵", name: "Monkey Face", keywords: ["monkey"], category: .animals),
        .init(glyph: "🙈", name: "See-No-Evil Monkey", keywords: ["monkey", "no"], category: .animals),
        .init(glyph: "🙉", name: "Hear-No-Evil Monkey", keywords: ["monkey", "no"], category: .animals),
        .init(glyph: "🙊", name: "Speak-No-Evil Monkey", keywords: ["monkey", "no"], category: .animals),
        .init(glyph: "🐔", name: "Chicken", keywords: ["chicken", "hen"], category: .animals),
        .init(glyph: "🐧", name: "Penguin", keywords: ["penguin"], category: .animals),
        .init(glyph: "🐦", name: "Bird", keywords: ["bird"], category: .animals),
        .init(glyph: "🦆", name: "Duck", keywords: ["duck"], category: .animals),
        .init(glyph: "🦉", name: "Owl", keywords: ["owl", "bird"], category: .animals),
        .init(glyph: "🐺", name: "Wolf", keywords: ["wolf"], category: .animals),
        .init(glyph: "🐗", name: "Boar", keywords: ["boar", "pig"], category: .animals),
        .init(glyph: "🐴", name: "Horse Face", keywords: ["horse"], category: .animals),
        .init(glyph: "🦄", name: "Unicorn", keywords: ["unicorn", "horse"], category: .animals),
        .init(glyph: "🐝", name: "Honeybee", keywords: ["bee", "insect"], category: .animals),
        .init(glyph: "🐛", name: "Bug", keywords: ["bug", "insect", "worm"], category: .animals),
        .init(glyph: "🦋", name: "Butterfly", keywords: ["butterfly", "insect"], category: .animals),
        .init(glyph: "🐌", name: "Snail", keywords: ["snail", "slow"], category: .animals),
        .init(glyph: "🐞", name: "Lady Beetle", keywords: ["ladybug", "beetle"], category: .animals),
        .init(glyph: "🐟", name: "Fish", keywords: ["fish"], category: .animals),
        .init(glyph: "🐠", name: "Tropical Fish", keywords: ["fish", "tropical"], category: .animals),
        .init(glyph: "🐬", name: "Dolphin", keywords: ["dolphin"], category: .animals),
        .init(glyph: "🐳", name: "Spouting Whale", keywords: ["whale"], category: .animals),
        .init(glyph: "🐙", name: "Octopus", keywords: ["octopus"], category: .animals),
        .init(glyph: "🦀", name: "Crab", keywords: ["crab"], category: .animals),
        .init(glyph: "🐊", name: "Crocodile", keywords: ["crocodile", "alligator"], category: .animals),
        .init(glyph: "🐍", name: "Snake", keywords: ["snake", "serpent"], category: .animals),
        .init(glyph: "🐉", name: "Dragon", keywords: ["dragon"], category: .animals),
        .init(glyph: "🌴", name: "Palm Tree", keywords: ["palm", "tree", "tropical"], category: .animals),
        .init(glyph: "🌵", name: "Cactus", keywords: ["cactus", "plant"], category: .animals),
        .init(glyph: "🎄", name: "Christmas Tree", keywords: ["christmas", "tree"], category: .animals),
        .init(glyph: "🌲", name: "Evergreen Tree", keywords: ["tree", "pine"], category: .animals),
        .init(glyph: "🌳", name: "Deciduous Tree", keywords: ["tree"], category: .animals),
        .init(glyph: "🌷", name: "Tulip", keywords: ["tulip", "flower"], category: .animals),
        .init(glyph: "🌹", name: "Rose", keywords: ["rose", "flower", "love"], category: .animals),
        .init(glyph: "🌺", name: "Hibiscus", keywords: ["hibiscus", "flower"], category: .animals),
        .init(glyph: "🌸", name: "Cherry Blossom", keywords: ["blossom", "flower", "sakura"], category: .animals),
        .init(glyph: "🌼", name: "Blossom", keywords: ["flower", "blossom"], category: .animals),
        .init(glyph: "🌻", name: "Sunflower", keywords: ["sunflower", "flower"], category: .animals),
        .init(glyph: "🍀", name: "Four Leaf Clover", keywords: ["clover", "luck"], category: .animals),
        .init(glyph: "🍁", name: "Maple Leaf", keywords: ["leaf", "maple", "fall"], category: .animals),
        .init(glyph: "🌍", name: "Globe Showing Europe-Australia", keywords: ["earth", "world", "globe"], category: .animals),

        // Food & Drink
        .init(glyph: "🍏", name: "Green Apple", keywords: ["apple", "green", "fruit"], category: .food),
        .init(glyph: "🍎", name: "Red Apple", keywords: ["apple", "red", "fruit"], category: .food),
        .init(glyph: "🍐", name: "Pear", keywords: ["pear", "fruit"], category: .food),
        .init(glyph: "🍊", name: "Tangerine", keywords: ["orange", "fruit"], category: .food),
        .init(glyph: "🍋", name: "Lemon", keywords: ["lemon", "fruit", "sour"], category: .food),
        .init(glyph: "🍌", name: "Banana", keywords: ["banana", "fruit"], category: .food),
        .init(glyph: "🍉", name: "Watermelon", keywords: ["watermelon", "fruit", "summer"], category: .food),
        .init(glyph: "🍇", name: "Grapes", keywords: ["grapes", "fruit", "wine"], category: .food),
        .init(glyph: "🍓", name: "Strawberry", keywords: ["strawberry", "fruit"], category: .food),
        .init(glyph: "🍈", name: "Melon", keywords: ["melon", "fruit"], category: .food),
        .init(glyph: "🍒", name: "Cherries", keywords: ["cherry", "fruit"], category: .food),
        .init(glyph: "🍑", name: "Peach", keywords: ["peach", "fruit"], category: .food),
        .init(glyph: "🥭", name: "Mango", keywords: ["mango", "fruit"], category: .food),
        .init(glyph: "🍍", name: "Pineapple", keywords: ["pineapple", "fruit"], category: .food),
        .init(glyph: "🥥", name: "Coconut", keywords: ["coconut", "fruit"], category: .food),
        .init(glyph: "🥝", name: "Kiwi Fruit", keywords: ["kiwi", "fruit"], category: .food),
        .init(glyph: "🍅", name: "Tomato", keywords: ["tomato", "vegetable"], category: .food),
        .init(glyph: "🥑", name: "Avocado", keywords: ["avocado", "fruit"], category: .food),
        .init(glyph: "🌶️", name: "Hot Pepper", keywords: ["pepper", "spicy", "hot"], category: .food),
        .init(glyph: "🥕", name: "Carrot", keywords: ["carrot", "vegetable"], category: .food),
        .init(glyph: "🌽", name: "Ear of Corn", keywords: ["corn", "maize"], category: .food),
        .init(glyph: "🥦", name: "Broccoli", keywords: ["broccoli", "vegetable"], category: .food),
        .init(glyph: "🍞", name: "Bread", keywords: ["bread", "loaf"], category: .food),
        .init(glyph: "🥐", name: "Croissant", keywords: ["croissant", "bread", "french"], category: .food),
        .init(glyph: "🧀", name: "Cheese Wedge", keywords: ["cheese"], category: .food),
        .init(glyph: "🍳", name: "Cooking", keywords: ["egg", "breakfast", "fry"], category: .food),
        .init(glyph: "🍔", name: "Hamburger", keywords: ["burger", "hamburger"], category: .food),
        .init(glyph: "🍟", name: "French Fries", keywords: ["fries", "potato"], category: .food),
        .init(glyph: "🍕", name: "Pizza", keywords: ["pizza", "slice"], category: .food),
        .init(glyph: "🌭", name: "Hot Dog", keywords: ["hotdog", "frankfurt"], category: .food),
        .init(glyph: "🥪", name: "Sandwich", keywords: ["sandwich"], category: .food),
        .init(glyph: "🌮", name: "Taco", keywords: ["taco", "mexican"], category: .food),
        .init(glyph: "🌯", name: "Burrito", keywords: ["burrito", "mexican", "wrap"], category: .food),
        .init(glyph: "🍝", name: "Spaghetti", keywords: ["pasta", "spaghetti", "noodle"], category: .food),
        .init(glyph: "🍜", name: "Steaming Bowl", keywords: ["ramen", "noodle", "soup"], category: .food),
        .init(glyph: "🍣", name: "Sushi", keywords: ["sushi", "japanese"], category: .food),
        .init(glyph: "🍦", name: "Soft Ice Cream", keywords: ["icecream", "dessert"], category: .food),
        .init(glyph: "🍩", name: "Doughnut", keywords: ["donut", "doughnut", "dessert"], category: .food),
        .init(glyph: "🍪", name: "Cookie", keywords: ["cookie", "dessert", "chocolate"], category: .food),
        .init(glyph: "🍫", name: "Chocolate Bar", keywords: ["chocolate", "candy"], category: .food),
        .init(glyph: "🍬", name: "Candy", keywords: ["candy", "sweet"], category: .food),
        .init(glyph: "🍭", name: "Lollipop", keywords: ["lollipop", "candy"], category: .food),
        .init(glyph: "🎂", name: "Birthday Cake", keywords: ["cake", "birthday", "party"], category: .food),
        .init(glyph: "🍰", name: "Shortcake", keywords: ["cake", "dessert", "strawberry"], category: .food),
        .init(glyph: "☕", name: "Hot Beverage", keywords: ["coffee", "tea", "drink", "hot"], category: .food),
        .init(glyph: "🍵", name: "Teacup Without Handle", keywords: ["tea", "green", "drink"], category: .food),
        .init(glyph: "🍺", name: "Beer Mug", keywords: ["beer", "drink", "mug"], category: .food),
        .init(glyph: "🍻", name: "Clinking Beer Mugs", keywords: ["beer", "cheers", "drink"], category: .food),
        .init(glyph: "🍷", name: "Wine Glass", keywords: ["wine", "drink"], category: .food),
        .init(glyph: "🥂", name: "Clinking Glasses", keywords: ["cheers", "celebrate", "champagne"], category: .food),
        .init(glyph: "🍹", name: "Tropical Drink", keywords: ["cocktail", "tropical", "drink"], category: .food),
        .init(glyph: "🥤", name: "Cup with Straw", keywords: ["soda", "drink", "cup"], category: .food),
        .init(glyph: "🧊", name: "Ice", keywords: ["ice", "cold", "cube"], category: .food),
        .init(glyph: "🧂", name: "Salt", keywords: ["salt", "seasoning"], category: .food),

        // Activities
        .init(glyph: "⚽", name: "Soccer Ball", keywords: ["soccer", "football", "ball"], category: .activities),
        .init(glyph: "🏀", name: "Basketball", keywords: ["basketball", "ball", "hoops"], category: .activities),
        .init(glyph: "🏈", name: "American Football", keywords: ["football", "ball"], category: .activities),
        .init(glyph: "⚾", name: "Baseball", keywords: ["baseball", "ball"], category: .activities),
        .init(glyph: "🎾", name: "Tennis", keywords: ["tennis", "ball", "racquet"], category: .activities),
        .init(glyph: "🏐", name: "Volleyball", keywords: ["volleyball", "ball"], category: .activities),
        .init(glyph: "🏉", name: "Rugby Football", keywords: ["rugby", "football"], category: .activities),
        .init(glyph: "🎱", name: "Pool 8 Ball", keywords: ["pool", "billiards", "8ball"], category: .activities),
        .init(glyph: "🏓", name: "Ping Pong", keywords: ["tabletennis", "pingpong", "paddle"], category: .activities),
        .init(glyph: "🏸", name: "Badminton", keywords: ["badminton", "racquet", "shuttlecock"], category: .activities),
        .init(glyph: "🥅", name: "Goal Net", keywords: ["goal", "net"], category: .activities),
        .init(glyph: "🏒", name: "Ice Hockey", keywords: ["hockey", "puck", "stick"], category: .activities),
        .init(glyph: "🏑", name: "Field Hockey", keywords: ["hockey", "stick"], category: .activities),
        .init(glyph: "⛳", name: "Flag in Hole", keywords: ["golf", "hole", "flag"], category: .activities),
        .init(glyph: "🏹", name: "Bow and Arrow", keywords: ["bow", "arrow", "archery"], category: .activities),
        .init(glyph: "🎣", name: "Fishing Pole", keywords: ["fishing", "pole", "fish"], category: .activities),
        .init(glyph: "🥊", name: "Boxing Glove", keywords: ["boxing", "glove", "fight"], category: .activities),
        .init(glyph: "🥋", name: "Martial Arts Uniform", keywords: ["martialarts", "judo", "karate"], category: .activities),
        .init(glyph: "⛸️", name: "Ice Skate", keywords: ["iceskate", "skate", "ice"], category: .activities),
        .init(glyph: "🥌", name: "Curling Stone", keywords: ["curling", "stone"], category: .activities),
        .init(glyph: "🎿", name: "Skis", keywords: ["ski", "snow", "winter"], category: .activities),
        .init(glyph: "⛷️", name: "Skier", keywords: ["ski", "snow", "winter"], category: .activities),
        .init(glyph: "🏂", name: "Snowboarder", keywords: ["snowboard", "snow", "winter"], category: .activities),
        .init(glyph: "🏋️", name: "Person Lifting Weights", keywords: ["weight", "lift", "gym"], category: .activities),
        .init(glyph: "🤸", name: "Person Cartwheeling", keywords: ["cartwheel", "gymnastics"], category: .activities),
        .init(glyph: "⛹️", name: "Person Bouncing Ball", keywords: ["ball", "bounce", "basketball"], category: .activities),
        .init(glyph: "🤽", name: "Person Playing Water Polo", keywords: ["waterpolo", "ball"], category: .activities),
        .init(glyph: "🤾", name: "Person Playing Handball", keywords: ["handball", "ball"], category: .activities),
        .init(glyph: "🏌️", name: "Person Golfing", keywords: ["golf", "swing"], category: .activities),
        .init(glyph: "🏇", name: "Horse Racing", keywords: ["horse", "race"], category: .activities),
        .init(glyph: "🧘", name: "Person in Lotus Position", keywords: ["yoga", "meditation", "lotus"], category: .activities),
        .init(glyph: "🏆", name: "Trophy", keywords: ["trophy", "win", "award"], category: .activities),
        .init(glyph: "🥇", name: "1st Place Medal", keywords: ["gold", "first", "medal"], category: .activities),
        .init(glyph: "🥈", name: "2nd Place Medal", keywords: ["silver", "second", "medal"], category: .activities),
        .init(glyph: "🥉", name: "3rd Place Medal", keywords: ["bronze", "third", "medal"], category: .activities),
        .init(glyph: "🏅", name: "Sports Medal", keywords: ["medal", "award"], category: .activities),
        .init(glyph: "🎖️", name: "Military Medal", keywords: ["medal", "military"], category: .activities),
        .init(glyph: "🎗️", name: "Reminder Ribbon", keywords: ["ribbon", "reminder"], category: .activities),
        .init(glyph: "🎫", name: "Ticket", keywords: ["ticket", "admission"], category: .activities),
        .init(glyph: "🎟️", name: "Admission Tickets", keywords: ["ticket", "admission", "event"], category: .activities),
        .init(glyph: "🎪", name: "Circus Tent", keywords: ["circus", "tent"], category: .activities),
        .init(glyph: "🎭", name: "Performing Arts", keywords: ["theater", "drama", "mask"], category: .activities),
        .init(glyph: "🎨", name: "Artist Palette", keywords: ["art", "paint", "palette", "design"], category: .activities),
        .init(glyph: "🎬", name: "Clapper Board", keywords: ["movie", "film", "clapper"], category: .activities),
        .init(glyph: "🎤", name: "Microphone", keywords: ["mic", "microphone", "sing", "karaoke"], category: .activities),
        .init(glyph: "🎧", name: "Headphone", keywords: ["headphone", "music", "audio"], category: .activities),
        .init(glyph: "🎼", name: "Musical Score", keywords: ["music", "score", "sheet"], category: .activities),
        .init(glyph: "🎹", name: "Musical Keyboard", keywords: ["piano", "keyboard", "music"], category: .activities),
        .init(glyph: "🥁", name: "Drum", keywords: ["drum", "music"], category: .activities),
        .init(glyph: "🎷", name: "Saxophone", keywords: ["sax", "saxophone", "music"], category: .activities),
        .init(glyph: "🎺", name: "Trumpet", keywords: ["trumpet", "music", "horn"], category: .activities),
        .init(glyph: "🎸", name: "Guitar", keywords: ["guitar", "music", "rock"], category: .activities),
        .init(glyph: "🎻", name: "Violin", keywords: ["violin", "music"], category: .activities),
        .init(glyph: "🎲", name: "Game Die", keywords: ["dice", "die", "game"], category: .activities),
        .init(glyph: "🎯", name: "Direct Hit", keywords: ["dart", "target", "bullseye"], category: .activities),
        .init(glyph: "🎳", name: "Bowling", keywords: ["bowling", "strike"], category: .activities),
        .init(glyph: "🎮", name: "Video Game", keywords: ["game", "controller", "play"], category: .activities),
        .init(glyph: "🕹️", name: "Joystick", keywords: ["game", "joystick"], category: .activities),
        .init(glyph: "🎰", name: "Slot Machine", keywords: ["slot", "casino", "jackpot", "luck"], category: .activities),
        .init(glyph: "🧩", name: "Puzzle Piece", keywords: ["puzzle", "jigsaw", "piece"], category: .activities),

        // Travel & Places
        .init(glyph: "🚗", name: "Automobile", keywords: ["car", "automobile"], category: .travel),
        .init(glyph: "🚕", name: "Taxi", keywords: ["taxi", "cab", "uber"], category: .travel),
        .init(glyph: "🚙", name: "Sport Utility Vehicle", keywords: ["suv", "car"], category: .travel),
        .init(glyph: "🏎️", name: "Racing Car", keywords: ["race", "car", "formula"], category: .travel),
        .init(glyph: "🚓", name: "Police Car", keywords: ["police", "car"], category: .travel),
        .init(glyph: "🚑", name: "Ambulance", keywords: ["ambulance", "medical"], category: .travel),
        .init(glyph: "🚒", name: "Fire Engine", keywords: ["fire", "engine", "truck"], category: .travel),
        .init(glyph: "🚐", name: "Minibus", keywords: ["minibus", "van"], category: .travel),
        .init(glyph: "🚌", name: "Bus", keywords: ["bus", "transport"], category: .travel),
        .init(glyph: "🚍", name: "Oncoming Bus", keywords: ["bus"], category: .travel),
        .init(glyph: "🚎", name: "Trolleybus", keywords: ["trolley", "bus"], category: .travel),
        .init(glyph: "🚲", name: "Bicycle", keywords: ["bike", "bicycle", "cycle"], category: .travel),
        .init(glyph: "🛴", name: "Kick Scooter", keywords: ["scooter", "kick"], category: .travel),
        .init(glyph: "🛵", name: "Motor Scooter", keywords: ["scooter", "motor", "vespa"], category: .travel),
        .init(glyph: "🏍️", name: "Motorcycle", keywords: ["motorcycle", "bike"], category: .travel),
        .init(glyph: "🚨", name: "Police Car Light", keywords: ["police", "light", "beacon"], category: .travel),
        .init(glyph: "🚔", name: "Oncoming Police Car", keywords: ["police", "car"], category: .travel),
        .init(glyph: "🚍", name: "Oncoming Bus", keywords: ["bus"], category: .travel),
        .init(glyph: "🚘", name: "Oncoming Automobile", keywords: ["car"], category: .travel),
        .init(glyph: "🚖", name: "Oncoming Taxi", keywords: ["taxi"], category: .travel),
        .init(glyph: "🚡", name: "Aerial Tramway", keywords: ["tram", "cable", "aerial"], category: .travel),
        .init(glyph: "🚠", name: "Mountain Cableway", keywords: ["cable", "mountain"], category: .travel),
        .init(glyph: "🚟", name: "Suspension Railway", keywords: ["railway", "suspension"], category: .travel),
        .init(glyph: "🚃", name: "Railway Car", keywords: ["railway", "tram", "car"], category: .travel),
        .init(glyph: "🚋", name: "Tram Car", keywords: ["tram", "streetcar"], category: .travel),
        .init(glyph: "🚞", name: "Mountain Railway", keywords: ["railway", "mountain"], category: .travel),
        .init(glyph: "🚝", name: "Monorail", keywords: ["monorail", "railway"], category: .travel),
        .init(glyph: "🚄", name: "High-Speed Train", keywords: ["train", "bullet", "fast"], category: .travel),
        .init(glyph: "🚅", name: "Bullet Train", keywords: ["train", "bullet", "shinkansen"], category: .travel),
        .init(glyph: "🚂", name: "Locomotive", keywords: ["train", "locomotive"], category: .travel),
        .init(glyph: "🚆", name: "Train", keywords: ["train", "railway"], category: .travel),
        .init(glyph: "🚇", name: "Metro", keywords: ["metro", "subway", "underground"], category: .travel),
        .init(glyph: "🚊", name: "Tram", keywords: ["tram", "streetcar"], category: .travel),
        .init(glyph: "🚉", name: "Station", keywords: ["station", "train"], category: .travel),
        .init(glyph: "✈️", name: "Airplane", keywords: ["airplane", "plane", "flight", "fly"], category: .travel),
        .init(glyph: "🛫", name: "Airplane Departure", keywords: ["airplane", "departure", "takeoff"], category: .travel),
        .init(glyph: "🛬", name: "Airplane Arrival", keywords: ["airplane", "arrival", "landing"], category: .travel),
        .init(glyph: "🚁", name: "Helicopter", keywords: ["helicopter", "chopper"], category: .travel),
        .init(glyph: "🚟", name: "Suspension Railway", keywords: ["railway"], category: .travel),
        .init(glyph: "🛩️", name: "Small Airplane", keywords: ["airplane", "small", "plane"], category: .travel),
        .init(glyph: "🚀", name: "Rocket", keywords: ["rocket", "launch", "space"], category: .travel),
        .init(glyph: "🛸", name: "Flying Saucer", keywords: ["ufo", "saucer", "alien"], category: .travel),
        .init(glyph: "🚁", name: "Helicopter", keywords: ["helicopter"], category: .travel),
        .init(glyph: "⛵", name: "Sailboat", keywords: ["sailboat", "sail", "boat"], category: .travel),
        .init(glyph: "🚤", name: "Speedboat", keywords: ["speedboat", "boat", "fast"], category: .travel),
        .init(glyph: "🛳️", name: "Passenger Ship", keywords: ["ship", "passenger", "cruise"], category: .travel),
        .init(glyph: "⛴️", name: "Ferry", keywords: ["ferry", "boat"], category: .travel),
        .init(glyph: "🚢", name: "Ship", keywords: ["ship", "boat"], category: .travel),
        .init(glyph: "⚓", name: "Anchor", keywords: ["anchor", "ship", "sea"], category: .travel),
        .init(glyph: "⛽", name: "Fuel Pump", keywords: ["fuel", "gas", "pump"], category: .travel),
        .init(glyph: "🚧", name: "Construction", keywords: ["construction", "barrier", "road"], category: .travel),
        .init(glyph: "🚦", name: "Vertical Traffic Light", keywords: ["traffic", "light", "signal"], category: .travel),
        .init(glyph: "🚥", name: "Horizontal Traffic Light", keywords: ["traffic", "light"], category: .travel),
        .init(glyph: "🗺️", name: "World Map", keywords: ["map", "world"], category: .travel),
        .init(glyph: "🗿", name: "Moai", keywords: ["moai", "statue", "easter"], category: .travel),
        .init(glyph: "🗽", name: "Statue of Liberty", keywords: ["liberty", "statue", "nyc"], category: .travel),
        .init(glyph: "🗼", name: "Tokyo Tower", keywords: ["tokyo", "tower"], category: .travel),
        .init(glyph: "🏰", name: "Castle", keywords: ["castle", "european", "medieval"], category: .travel),
        .init(glyph: "🏯", name: "Japanese Castle", keywords: ["castle", "japanese"], category: .travel),
        .init(glyph: "🏟️", name: "Stadium", keywords: ["stadium", "sports"], category: .travel),
        .init(glyph: "🎡", name: "Ferris Wheel", keywords: ["ferris", "wheel", "amusement"], category: .travel),
        .init(glyph: "🎢", name: "Roller Coaster", keywords: ["rollercoaster", "amusement"], category: .travel),
        .init(glyph: "🎠", name: "Carousel Horse", keywords: ["carousel", "horse", "amusement"], category: .travel),
        .init(glyph: "⛲", name: "Fountain", keywords: ["fountain", "water"], category: .travel),
        .init(glyph: "⛱️", name: "Umbrella on Ground", keywords: ["umbrella", "beach", "umbrella"], category: .travel),
        .init(glyph: "🏖️", name: "Beach with Umbrella", keywords: ["beach", "umbrella", "sand"], category: .travel),
        .init(glyph: "🏝️", name: "Desert Island", keywords: ["island", "desert", "tropical"], category: .travel),
        .init(glyph: "⛰️", name: "Mountain", keywords: ["mountain"], category: .travel),
        .init(glyph: "🏔️", name: "Snow-Capped Mountain", keywords: ["mountain", "snow"], category: .travel),
        .init(glyph: "🗻", name: "Mount Fuji", keywords: ["fuji", "mountain", "volcano"], category: .travel),
        .init(glyph: "🌋", name: "Volcano", keywords: ["volcano", "eruption"], category: .travel),
        .init(glyph: "🏕️", name: "Camping", keywords: ["camping", "tent", "outdoor"], category: .travel),
        .init(glyph: "⛺", name: "Tent", keywords: ["tent", "camping"], category: .travel),
        .init(glyph: "🏠", name: "House", keywords: ["house", "home"], category: .travel),
        .init(glyph: "🏡", name: "House with Garden", keywords: ["house", "garden", "home"], category: .travel),
        .init(glyph: "🏢", name: "Office Building", keywords: ["office", "building"], category: .travel),
        .init(glyph: "🏣", name: "Japanese Post Office", keywords: ["post", "office"], category: .travel),
        .init(glyph: "🏥", name: "Hospital", keywords: ["hospital", "medical"], category: .travel),
        .init(glyph: "🏦", name: "Bank", keywords: ["bank", "money"], category: .travel),
        .init(glyph: "🏨", name: "Hotel", keywords: ["hotel", "building"], category: .travel),
        .init(glyph: "🏩", name: "Love Hotel", keywords: ["hotel", "love"], category: .travel),
        .init(glyph: "🏪", name: "Convenience Store", keywords: ["store", "convenience", "shop"], category: .travel),
        .init(glyph: "🏫", name: "School", keywords: ["school", "building"], category: .travel),
        .init(glyph: "🏬", name: "Department Store", keywords: ["store", "department", "shop"], category: .travel),
        .init(glyph: "🏭", name: "Factory", keywords: ["factory", "industrial"], category: .travel),
        .init(glyph: "🏯", name: "Japanese Castle", keywords: ["castle"], category: .travel),
        .init(glyph: "💒", name: "Wedding", keywords: ["wedding", "chapel", "love"], category: .travel),
        .init(glyph: "🗼", name: "Tokyo Tower", keywords: ["tokyo", "tower"], category: .travel),
        .init(glyph: "🌅", name: "Sunrise", keywords: ["sunrise", "morning"], category: .travel),
        .init(glyph: "🌆", name: "Cityscape at Dusk", keywords: ["dusk", "city", "sunset"], category: .travel),
        .init(glyph: "🌇", name: "Sunset", keywords: ["sunset", "city"], category: .travel),
        .init(glyph: "🌃", name: "Night with Stars", keywords: ["night", "stars", "city"], category: .travel),
        .init(glyph: "🌄", name: "Sunrise Over Mountains", keywords: ["sunrise", "mountains", "morning"], category: .travel),
        .init(glyph: "🌤️", name: "Sun Behind Small Cloud", keywords: ["sun", "cloud", "weather"], category: .travel),
        .init(glyph: "⛅", name: "Sun Behind Cloud", keywords: ["sun", "cloud", "weather"], category: .travel),
        .init(glyph: "🌥️", name: "Cloud", keywords: ["cloud", "weather"], category: .travel),
        .init(glyph: "🌦️", name: "Sun Behind Rain Cloud", keywords: ["sun", "rain", "weather"], category: .travel),
        .init(glyph: "🌧️", name: "Cloud with Rain", keywords: ["rain", "cloud", "weather"], category: .travel),
        .init(glyph: "⛈️", name: "Cloud with Lightning and Rain", keywords: ["storm", "thunder", "rain"], category: .travel),
        .init(glyph: "🌩️", name: "Cloud with Lightning", keywords: ["lightning", "cloud", "storm"], category: .travel),
        .init(glyph: "🌨️", name: "Cloud with Snow", keywords: ["snow", "cloud", "weather"], category: .travel),
        .init(glyph: "❄️", name: "Snowflake", keywords: ["snow", "cold", "winter", "flake"], category: .travel),
        .init(glyph: "🌊", name: "Water Wave", keywords: ["wave", "water", "ocean", "sea"], category: .travel),
        .init(glyph: "💨", name: "Dashing Away", keywords: ["wind", "dash", "fast"], category: .travel),
        .init(glyph: "🌪️", name: "Tornado", keywords: ["tornado", "twister", "storm"], category: .travel),
        .init(glyph: "🌫️", name: "Fog", keywords: ["fog", "weather"], category: .travel),
        .init(glyph: "🌈", name: "Rainbow", keywords: ["rainbow", "rain", "color"], category: .travel),
        .init(glyph: "☔", name: "Umbrella with Rain Drops", keywords: ["umbrella", "rain"], category: .travel),
        .init(glyph: "💧", name: "Droplet", keywords: ["drop", "water", "drip"], category: .travel),
        .init(glyph: "🔥", name: "Fire", keywords: ["fire", "flame", "hot", "lit"], category: .travel),
        .init(glyph: "✨", name: "Sparkles", keywords: ["sparkle", "shiny", "stars", "magic"], category: .travel),
        .init(glyph: "⭐", name: "Star", keywords: ["star", "night"], category: .travel),
        .init(glyph: "🌟", name: "Glowing Star", keywords: ["star", "glow", "shine"], category: .travel),
        .init(glyph: "💫", name: "Dizzy", keywords: ["dizzy", "star"], category: .travel),
        .init(glyph: "⚡", name: "High Voltage", keywords: ["lightning", "voltage", "energy", "zap", "fast"], category: .travel),
        .init(glyph: "☁️", name: "Cloud", keywords: ["cloud", "weather"], category: .travel),
        .init(glyph: "☀️", name: "Sun", keywords: ["sun", "sunny", "weather"], category: .travel),
        .init(glyph: "🌤️", name: "Sun Behind Small Cloud", keywords: ["sun", "cloud"], category: .travel),
        .init(glyph: "⛅", name: "Sun Behind Cloud", keywords: ["sun", "cloud"], category: .travel),
        .init(glyph: "🌥️", name: "Cloud", keywords: ["cloud"], category: .travel),
        .init(glyph: "🌦️", name: "Sun Behind Rain Cloud", keywords: ["sun", "rain"], category: .travel),
        .init(glyph: "🌧️", name: "Cloud with Rain", keywords: ["rain"], category: .travel),
        .init(glyph: "🌩️", name: "Cloud with Lightning", keywords: ["lightning"], category: .travel),
        .init(glyph: "🌨️", name: "Cloud with Snow", keywords: ["snow"], category: .travel),
        .init(glyph: "🌪️", name: "Tornado", keywords: ["tornado"], category: .travel),
        .init(glyph: "🌫️", name: "Fog", keywords: ["fog"], category: .travel),
        .init(glyph: "🌬️", name: "Wind Face", keywords: ["wind", "blow"], category: .travel),
        .init(glyph: "🌀", name: "Cyclone", keywords: ["cyclone", "hurricane", "swirl"], category: .travel),
        .init(glyph: "🌈", name: "Rainbow", keywords: ["rainbow"], category: .travel),
        .init(glyph: "🌂", name: "Closed Umbrella", keywords: ["umbrella", "rain"], category: .travel),
        .init(glyph: "☂️", name: "Umbrella", keywords: ["umbrella", "rain"], category: .travel),
        .init(glyph: "☔", name: "Umbrella with Rain Drops", keywords: ["umbrella", "rain"], category: .travel),
        .init(glyph: "⛱️", name: "Umbrella on Ground", keywords: ["umbrella"], category: .travel),
        .init(glyph: "⚡", name: "High Voltage", keywords: ["lightning", "zap"], category: .travel),
        .init(glyph: "❄️", name: "Snowflake", keywords: ["snow"], category: .travel),
        .init(glyph: "☃️", name: "Snowman", keywords: ["snowman", "snow"], category: .travel),
        .init(glyph: "⛄", name: "Snowman Without Snow", keywords: ["snowman", "snow"], category: .travel),
        .init(glyph: "☄️", name: "Comet", keywords: ["comet", "space"], category: .travel),
        .init(glyph: "🔥", name: "Fire", keywords: ["fire"], category: .travel),
        .init(glyph: "💧", name: "Droplet", keywords: ["drop", "water"], category: .travel),
        .init(glyph: "🌊", name: "Water Wave", keywords: ["wave", "sea"], category: .travel),

        // Objects
        .init(glyph: "⌚", name: "Watch", keywords: ["watch", "time", "clock"], category: .objects),
        .init(glyph: "📱", name: "Mobile Phone", keywords: ["phone", "mobile", "cell"], category: .objects),
        .init(glyph: "📲", name: "Mobile Phone with Arrow", keywords: ["phone", "call"], category: .objects),
        .init(glyph: "💻", name: "Laptop", keywords: ["laptop", "computer", "notebook"], category: .objects),
        .init(glyph: "⌨️", name: "Keyboard", keywords: ["keyboard", "type", "computer"], category: .objects),
        .init(glyph: "🖥️", name: "Desktop Computer", keywords: ["computer", "desktop", "imac"], category: .objects),
        .init(glyph: "🖨️", name: "Printer", keywords: ["printer", "print"], category: .objects),
        .init(glyph: "🖱️", name: "Computer Mouse", keywords: ["mouse", "computer"], category: .objects),
        .init(glyph: "🖲️", name: "Trackball", keywords: ["trackball"], category: .objects),
        .init(glyph: "🕹️", name: "Joystick", keywords: ["joystick", "game"], category: .objects),
        .init(glyph: "🗜️", name: "Clamp", keywords: ["clamp", "tool"], category: .objects),
        .init(glyph: "💽", name: "Computer Disk", keywords: ["disk", "minidisc"], category: .objects),
        .init(glyph: "💾", name: "Floppy Disk", keywords: ["floppy", "disk", "save"], category: .objects),
        .init(glyph: "💿", name: "Optical Disk", keywords: ["cd", "disk"], category: .objects),
        .init(glyph: "📀", name: "DVD", keywords: ["dvd", "disk"], category: .objects),
        .init(glyph: "📼", name: "Videocassette", keywords: ["vhs", "tape", "video"], category: .objects),
        .init(glyph: "📷", name: "Camera", keywords: ["camera", "photo"], category: .objects),
        .init(glyph: "📸", name: "Camera with Flash", keywords: ["camera", "flash", "photo"], category: .objects),
        .init(glyph: "📹", name: "Video Camera", keywords: ["camera", "video"], category: .objects),
        .init(glyph: "🎥", name: "Movie Camera", keywords: ["camera", "movie", "film"], category: .objects),
        .init(glyph: "📽️", name: "Film Projector", keywords: ["projector", "film"], category: .objects),
        .init(glyph: "🎞️", name: "Film Frames", keywords: ["film", "frames"], category: .objects),
        .init(glyph: "📞", name: "Telephone Receiver", keywords: ["phone", "telephone", "call"], category: .objects),
        .init(glyph: "☎️", name: "Telephone", keywords: ["phone", "telephone"], category: .objects),
        .init(glyph: "📟", name: "Pager", keywords: ["pager"], category: .objects),
        .init(glyph: "📠", name: "Fax Machine", keywords: ["fax"], category: .objects),
        .init(glyph: "📺", name: "Television", keywords: ["tv", "television"], category: .objects),
        .init(glyph: "📻", name: "Radio", keywords: ["radio"], category: .objects),
        .init(glyph: "🎙️", name: "Studio Microphone", keywords: ["mic", "microphone", "studio"], category: .objects),
        .init(glyph: "🎚️", name: "Level Slider", keywords: ["slider", "level"], category: .objects),
        .init(glyph: "🎛️", name: "Control Knobs", keywords: ["knobs", "control"], category: .objects),
        .init(glyph: "🧭", name: "Compass", keywords: ["compass", "navigation"], category: .objects),
        .init(glyph: "⏱️", name: "Stopwatch", keywords: ["stopwatch", "timer"], category: .objects),
        .init(glyph: "⏲️", name: "Timer Clock", keywords: ["timer", "clock"], category: .objects),
        .init(glyph: "⏰", name: "Alarm Clock", keywords: ["alarm", "clock", "wake"], category: .objects),
        .init(glyph: "🕰️", name: "Mantelpiece Clock", keywords: ["clock", "time"], category: .objects),
        .init(glyph: "⏳", name: "Hourglass with Flowing Sand", keywords: ["hourglass", "time", "sand"], category: .objects),
        .init(glyph: "⌛", name: "Hourglass Done", keywords: ["hourglass", "time"], category: .objects),
        .init(glyph: "📡", name: "Satellite Antenna", keywords: ["satellite", "antenna"], category: .objects),
        .init(glyph: "🔋", name: "Battery", keywords: ["battery", "power"], category: .objects),
        .init(glyph: "🔌", name: "Electric Plug", keywords: ["plug", "power", "electric"], category: .objects),
        .init(glyph: "💡", name: "Light Bulb", keywords: ["bulb", "light", "idea"], category: .objects),
        .init(glyph: "🔦", name: "Flashlight", keywords: ["flashlight", "light"], category: .objects),
        .init(glyph: "🕯️", name: "Candle", keywords: ["candle", "light"], category: .objects),
        .init(glyph: "🗑️", name: "Wastebasket", keywords: ["trash", "bin", "waste"], category: .objects),
        .init(glyph: "🛢️", name: "Oil Drum", keywords: ["oil", "drum", "barrel"], category: .objects),
        .init(glyph: "💸", name: "Money with Wings", keywords: ["money", "dollar", "wings"], category: .objects),
        .init(glyph: "💵", name: "Dollar Banknote", keywords: ["money", "dollar", "bill"], category: .objects),
        .init(glyph: "💴", name: "Yen Banknote", keywords: ["money", "yen"], category: .objects),
        .init(glyph: "💶", name: "Euro Banknote", keywords: ["money", "euro"], category: .objects),
        .init(glyph: "💷", name: "Pound Banknote", keywords: ["money", "pound"], category: .objects),
        .init(glyph: "💰", name: "Money Bag", keywords: ["money", "bag", "cash"], category: .objects),
        .init(glyph: "💳", name: "Credit Card", keywords: ["card", "credit", "money"], category: .objects),
        .init(glyph: "💎", name: "Gem Stone", keywords: ["gem", "diamond", "jewel"], category: .objects),
        .init(glyph: "⚖️", name: "Balance Scale", keywords: ["scale", "balance", "justice"], category: .objects),
        .init(glyph: "🔧", name: "Wrench", keywords: ["wrench", "tool", "fix"], category: .objects),
        .init(glyph: "🔨", name: "Hammer", keywords: ["hammer", "tool"], category: .objects),
        .init(glyph: "⚒️", name: "Hammer and Pick", keywords: ["hammer", "pick", "tools"], category: .objects),
        .init(glyph: "🛠️", name: "Hammer and Wrench", keywords: ["hammer", "wrench", "tools"], category: .objects),
        .init(glyph: "⛏️", name: "Pick", keywords: ["pick", "mine", "tool"], category: .objects),
        .init(glyph: "🔩", name: "Nut and Bolt", keywords: ["nut", "bolt", "tool"], category: .objects),
        .init(glyph: "⚙️", name: "Gear", keywords: ["gear", "settings", "cog"], category: .objects),
        .init(glyph: "🧱", name: "Brick", keywords: ["brick", "wall"], category: .objects),
        .init(glyph: "⛓️", name: "Chains", keywords: ["chain", "link"], category: .objects),
        .init(glyph: "🧲", name: "Magnet", keywords: ["magnet", "attract"], category: .objects),
        .init(glyph: "🔫", name: "Water Pistol", keywords: ["gun", "pistol", "water"], category: .objects),
        .init(glyph: "💣", name: "Bomb", keywords: ["bomb"], category: .objects),
        .init(glyph: "🧨", name: "Firecracker", keywords: ["firecracker", "explosive"], category: .objects),
        .init(glyph: "🪓", name: "Axe", keywords: ["axe", "hatchet", "tool"], category: .objects),
        .init(glyph: "🔪", name: "Kitchen Knife", keywords: ["knife", "kitchen", "cut"], category: .objects),
        .init(glyph: "🗡️", name: "Dagger", keywords: ["dagger", "knife"], category: .objects),
        .init(glyph: "⚔️", name: "Crossed Swords", keywords: ["sword", "crossed"], category: .objects),
        .init(glyph: "🛡️", name: "Shield", keywords: ["shield", "protect"], category: .objects),
        .init(glyph: "🚬", name: "Cigarette", keywords: ["cigarette", "smoking"], category: .objects),
        .init(glyph: "⚰️", name: "Coffin", keywords: ["coffin", "death"], category: .objects),
        .init(glyph: "⚱️", name: "Funeral Urn", keywords: ["urn", "funeral"], category: .objects),
        .init(glyph: "🏺", name: "Amphora", keywords: ["amphora", "vase"], category: .objects),
        .init(glyph: "🔮", name: "Crystal Ball", keywords: ["crystal", "ball", "fortune"], category: .objects),
        .init(glyph: "📿", name: "Prayer Beads", keywords: ["beads", "prayer"], category: .objects),
        .init(glyph: "🧿", name: "Nazar Amulet", keywords: ["nazar", "amulet"], category: .objects),
        .init(glyph: "💈", name: "Barber Pole", keywords: ["barber", "pole"], category: .objects),
        .init(glyph: "⚗️", name: "Alembic", keywords: ["alembic", "chemistry"], category: .objects),
        .init(glyph: "🔭", name: "Telescope", keywords: ["telescope", "stars"], category: .objects),
        .init(glyph: "🔬", name: "Microscope", keywords: ["microscope", "science"], category: .objects),
        .init(glyph: "🕳️", name: "Hole", keywords: ["hole"], category: .objects),
        .init(glyph: "💊", name: "Pill", keywords: ["pill", "medicine", "health"], category: .objects),
        .init(glyph: "💉", name: "Syringe", keywords: ["syringe", "injection", "health"], category: .objects),
        .init(glyph: "🩸", name: "Drop of Blood", keywords: ["blood", "drop"], category: .objects),
        .init(glyph: "🧬", name: "DNA", keywords: ["dna", "biology"], category: .objects),
        .init(glyph: "🦠", name: "Microbe", keywords: ["microbe", "germ", "bacteria"], category: .objects),
        .init(glyph: "🧪", name: "Test Tube", keywords: ["test", "tube", "chemistry"], category: .objects),
        .init(glyph: "🌡️", name: "Thermometer", keywords: ["thermometer", "temperature"], category: .objects),
        .init(glyph: "🧹", name: "Broom", keywords: ["broom", "clean"], category: .objects),
        .init(glyph: "🧺", name: "Basket", keywords: ["basket"], category: .objects),
        .init(glyph: "🧻", name: "Roll of Paper", keywords: ["paper", "roll", "toilet"], category: .objects),
        .init(glyph: "🚽", name: "Toilet", keywords: ["toilet", "wc"], category: .objects),
        .init(glyph: "🚿", name: "Shower", keywords: ["shower", "bath"], category: .objects),
        .init(glyph: "🛁", name: "Bathtub", keywords: ["bathtub", "bath"], category: .objects),
        .init(glyph: "🛀", name: "Person Taking Bath", keywords: ["bath", "bathtub"], category: .objects),
        .init(glyph: "🧼", name: "Soap", keywords: ["soap", "clean", "bar"], category: .objects),
        .init(glyph: "🧽", name: "Sponge", keywords: ["sponge", "clean"], category: .objects),
        .init(glyph: "🧴", name: "Lotion Bottle", keywords: ["lotion", "bottle"], category: .objects),
        .init(glyph: "🛎️", name: "Bellhop Bell", keywords: ["bell", "bellhop"], category: .objects),
        .init(glyph: "🔑", name: "Key", keywords: ["key", "lock", "password"], category: .objects),
        .init(glyph: "🗝️", name: "Old Key", keywords: ["key", "old"], category: .objects),
        .init(glyph: "🚪", name: "Door", keywords: ["door", "entry"], category: .objects),
        .init(glyph: "🛋️", name: "Couch and Lamp", keywords: ["couch", "sofa", "lamp"], category: .objects),
        .init(glyph: "🛏️", name: "Bed", keywords: ["bed", "sleep"], category: .objects),
        .init(glyph: "🛌", name: "Person in Bed", keywords: ["bed", "sleep"], category: .objects),
        .init(glyph: "🧸", name: "Teddy Bear", keywords: ["teddy", "bear", "toy"], category: .objects),
        .init(glyph: "🖼️", name: "Framed Picture", keywords: ["picture", "frame", "art"], category: .objects),
        .init(glyph: "🛍️", name: "Shopping Bags", keywords: ["shopping", "bags"], category: .objects),
        .init(glyph: "🛒", name: "Shopping Cart", keywords: ["cart", "shopping"], category: .objects),
        .init(glyph: "🎁", name: "Wrapped Gift", keywords: ["gift", "present"], category: .objects),
        .init(glyph: "🎈", name: "Balloon", keywords: ["balloon", "party"], category: .objects),
        .init(glyph: "🎏", name: "Carp Streamer", keywords: ["carp", "streamer"], category: .objects),
        .init(glyph: "🎀", name: "Ribbon", keywords: ["ribbon", "bow"], category: .objects),
        .init(glyph: "🪄", name: "Magic Wand", keywords: ["magic", "wand"], category: .objects),
        .init(glyph: "🪅", name: "Piñata", keywords: ["pinata", "party"], category: .objects),
        .init(glyph: "🎊", name: "Confetti Ball", keywords: ["confetti", "party"], category: .objects),
        .init(glyph: "🎉", name: "Party Popper", keywords: ["party", "celebrate", "popper"], category: .objects),
        .init(glyph: "🎎", name: "Japanese Dolls", keywords: ["dolls", "japanese"], category: .objects),
        .init(glyph: "🏮", name: "Red Paper Lantern", keywords: ["lantern", "red"], category: .objects),
        .init(glyph: "🎐", name: "Wind Chime", keywords: ["chime", "wind"], category: .objects),
        .init(glyph: "🧧", name: "Red Envelope", keywords: ["envelope", "red", "gift"], category: .objects),
        .init(glyph: "✉️", name: "Envelope", keywords: ["envelope", "mail", "email"], category: .objects),
        .init(glyph: "📩", name: "Envelope with Arrow", keywords: ["envelope", "send", "email"], category: .objects),
        .init(glyph: "📨", name: "Incoming Envelope", keywords: ["envelope", "incoming", "email"], category: .objects),
        .init(glyph: "📧", name: "E-Mail", keywords: ["email", "mail"], category: .objects),
        .init(glyph: "💌", name: "Love Letter", keywords: ["letter", "love", "mail"], category: .objects),
        .init(glyph: "📥", name: "Inbox Tray", keywords: ["inbox", "tray"], category: .objects),
        .init(glyph: "📤", name: "Outbox Tray", keywords: ["outbox", "tray"], category: .objects),
        .init(glyph: "📦", name: "Package", keywords: ["package", "box"], category: .objects),
        .init(glyph: "🏷️", name: "Label", keywords: ["label", "tag"], category: .objects),
        .init(glyph: "📪", name: "Closed Mailbox with Lowered Flag", keywords: ["mailbox", "mail"], category: .objects),
        .init(glyph: "📫", name: "Closed Mailbox with Raised Flag", keywords: ["mailbox", "mail"], category: .objects),
        .init(glyph: "📬", name: "Open Mailbox with Raised Flag", keywords: ["mailbox", "mail", "open"], category: .objects),
        .init(glyph: "📭", name: "Open Mailbox with Lowered Flag", keywords: ["mailbox", "mail", "open"], category: .objects),
        .init(glyph: "📮", name: "Postbox", keywords: ["postbox", "mail"], category: .objects),
        .init(glyph: "📯", name: "Postal Horn", keywords: ["horn", "postal"], category: .objects),
        .init(glyph: "📜", name: "Scroll", keywords: ["scroll", "paper"], category: .objects),
        .init(glyph: "📃", name: "Page with Curl", keywords: ["page", "paper"], category: .objects),
        .init(glyph: "📄", name: "Page Facing Up", keywords: ["page", "document", "paper"], category: .objects),
        .init(glyph: "📑", name: "Bookmark Tabs", keywords: ["bookmark", "tabs"], category: .objects),
        .init(glyph: "🧾", name: "Receipt", keywords: ["receipt", "accounting"], category: .objects),
        .init(glyph: "📊", name: "Bar Chart", keywords: ["chart", "bar", "graph"], category: .objects),
        .init(glyph: "📈", name: "Chart Increasing", keywords: ["chart", "graph", "up"], category: .objects),
        .init(glyph: "📉", name: "Chart Decreasing", keywords: ["chart", "graph", "down"], category: .objects),
        .init(glyph: "🗒️", name: "Spiral Notepad", keywords: ["notepad", "spiral"], category: .objects),
        .init(glyph: "🗓️", name: "Spiral Calendar", keywords: ["calendar", "spiral"], category: .objects),
        .init(glyph: "📆", name: "Tear-Off Calendar", keywords: ["calendar"], category: .objects),
        .init(glyph: "📅", name: "Calendar", keywords: ["calendar", "date"], category: .objects),
        .init(glyph: "🗑️", name: "Wastebasket", keywords: ["trash", "waste"], category: .objects),
        .init(glyph: "📇", name: "Card Index", keywords: ["card", "index"], category: .objects),
        .init(glyph: "🗃️", name: "Card File Box", keywords: ["card", "file", "box"], category: .objects),
        .init(glyph: "🗳️", name: "Ballot Box with Ballot", keywords: ["ballot", "vote"], category: .objects),
        .init(glyph: "🗄️", name: "File Cabinet", keywords: ["file", "cabinet"], category: .objects),
        .init(glyph: "📋", name: "Clipboard", keywords: ["clipboard", "board"], category: .objects),
        .init(glyph: "📁", name: "File Folder", keywords: ["folder", "file"], category: .objects),
        .init(glyph: "📂", name: "Open File Folder", keywords: ["folder", "open", "file"], category: .objects),
        .init(glyph: "🗂️", name: "Card Index Dividers", keywords: ["dividers", "index"], category: .objects),
        .init(glyph: "🗞️", name: "Rolled-Up Newspaper", keywords: ["newspaper", "news"], category: .objects),
        .init(glyph: "📰", name: "Newspaper", keywords: ["newspaper", "news", "press"], category: .objects),
        .init(glyph: "📓", name: "Notebook", keywords: ["notebook", "notes"], category: .objects),
        .init(glyph: "📔", name: "Notebook with Decorative Cover", keywords: ["notebook", "decorative"], category: .objects),
        .init(glyph: "📒", name: "Ledger", keywords: ["ledger", "notebook"], category: .objects),
        .init(glyph: "📕", name: "Closed Book", keywords: ["book", "closed", "read"], category: .objects),
        .init(glyph: "📗", name: "Green Book", keywords: ["book", "green", "read"], category: .objects),
        .init(glyph: "📘", name: "Blue Book", keywords: ["book", "blue", "read"], category: .objects),
        .init(glyph: "📙", name: "Orange Book", keywords: ["book", "orange", "read"], category: .objects),
        .init(glyph: "📚", name: "Books", keywords: ["books", "library", "read"], category: .objects),
        .init(glyph: "📖", name: "Open Book", keywords: ["book", "open", "read"], category: .objects),
        .init(glyph: "🔖", name: "Bookmark", keywords: ["bookmark"], category: .objects),
        .init(glyph: "🧷", name: "Safety Pin", keywords: ["pin", "safety"], category: .objects),
        .init(glyph: "🔗", name: "Link", keywords: ["link", "url"], category: .objects),
        .init(glyph: "📎", name: "Paperclip", keywords: ["paperclip", "attach"], category: .objects),
        .init(glyph: "🖇️", name: "Linked Paperclips", keywords: ["paperclip", "linked"], category: .objects),
        .init(glyph: "📐", name: "Triangular Ruler", keywords: ["ruler", "triangle"], category: .objects),
        .init(glyph: "📏", name: "Straight Ruler", keywords: ["ruler", "measure"], category: .objects),
        .init(glyph: "🧮", name: "Abacus", keywords: ["abacus", "calculate"], category: .objects),
        .init(glyph: "📌", name: "Pushpin", keywords: ["pushpin", "pin"], category: .objects),
        .init(glyph: "📍", name: "Round Pushpin", keywords: ["pushpin", "pin", "location"], category: .objects),
        .init(glyph: "✂️", name: "Scissors", keywords: ["scissors", "cut"], category: .objects),
        .init(glyph: "🖊️", name: "Pen", keywords: ["pen", "write"], category: .objects),
        .init(glyph: "🖋️", name: "Fountain Pen", keywords: ["pen", "fountain", "write"], category: .objects),
        .init(glyph: "✒️", name: "Black Nib", keywords: ["nib", "pen", "write"], category: .objects),
        .init(glyph: "🖌️", name: "Paintbrush", keywords: ["brush", "paint"], category: .objects),
        .init(glyph: "🖍️", name: "Crayon", keywords: ["crayon", "color"], category: .objects),
        .init(glyph: "✏️", name: "Pencil", keywords: ["pencil", "write"], category: .objects),
        .init(glyph: "🔍", name: "Magnifying Glass Tilted Left", keywords: ["search", "magnify", "zoom"], category: .objects),
        .init(glyph: "🔎", name: "Magnifying Glass Tilted Right", keywords: ["search", "magnify", "zoom"], category: .objects),
        .init(glyph: "🔏", name: "Locked with Pen", keywords: ["lock", "pen", "secure"], category: .objects),
        .init(glyph: "🔐", name: "Locked with Key", keywords: ["lock", "key", "secure"], category: .objects),
        .init(glyph: "🔒", name: "Locked", keywords: ["lock", "secure", "closed"], category: .objects),
        .init(glyph: "🔓", name: "Unlocked", keywords: ["unlock", "open", "unsecure"], category: .objects),

        // Symbols
        .init(glyph: "❤️", name: "Red Heart", keywords: ["heart", "love"], category: .symbols),
        .init(glyph: "🧡", name: "Orange Heart", keywords: ["heart", "orange"], category: .symbols),
        .init(glyph: "💛", name: "Yellow Heart", keywords: ["heart", "yellow"], category: .symbols),
        .init(glyph: "💚", name: "Green Heart", keywords: ["heart", "green"], category: .symbols),
        .init(glyph: "💙", name: "Blue Heart", keywords: ["heart", "blue"], category: .symbols),
        .init(glyph: "💜", name: "Purple Heart", keywords: ["heart", "purple"], category: .symbols),
        .init(glyph: "🖤", name: "Black Heart", keywords: ["heart", "black"], category: .symbols),
        .init(glyph: "🤍", name: "White Heart", keywords: ["heart", "white"], category: .symbols),
        .init(glyph: "🤎", name: "Brown Heart", keywords: ["heart", "brown"], category: .symbols),
        .init(glyph: "💔", name: "Broken Heart", keywords: ["heart", "broken"], category: .symbols),
        .init(glyph: "❣️", name: "Heart Exclamation", keywords: ["heart", "exclamation"], category: .symbols),
        .init(glyph: "💕", name: "Two Hearts", keywords: ["heart", "two"], category: .symbols),
        .init(glyph: "💞", name: "Revolving Hearts", keywords: ["heart", "revolving"], category: .symbols),
        .init(glyph: "💓", name: "Beating Heart", keywords: ["heart", "beat"], category: .symbols),
        .init(glyph: "💗", name: "Growing Heart", keywords: ["heart", "growing"], category: .symbols),
        .init(glyph: "💖", name: "Sparkling Heart", keywords: ["heart", "sparkle"], category: .symbols),
        .init(glyph: "💘", name: "Heart with Arrow", keywords: ["heart", "arrow", "cupid"], category: .symbols),
        .init(glyph: "💝", name: "Heart with Ribbon", keywords: ["heart", "ribbon", "gift"], category: .symbols),
        .init(glyph: "💟", name: "Heart Decoration", keywords: ["heart", "decoration"], category: .symbols),
        .init(glyph: "☮️", name: "Peace Symbol", keywords: ["peace"], category: .symbols),
        .init(glyph: "✝️", name: "Latin Cross", keywords: ["cross", "christian"], category: .symbols),
        .init(glyph: "☪️", name: "Star and Crescent", keywords: ["star", "crescent", "islam"], category: .symbols),
        .init(glyph: "🕉️", name: "Om", keywords: ["om", "hindu"], category: .symbols),
        .init(glyph: "☸️", name: "Wheel of Dharma", keywords: ["dharma", "wheel", "buddhism"], category: .symbols),
        .init(glyph: "✡️", name: "Star of David", keywords: ["star", "david", "judaism"], category: .symbols),
        .init(glyph: "🔯", name: "Dotted Six-Pointed Star", keywords: ["star", "six"], category: .symbols),
        .init(glyph: "🕎", name: "Menorah", keywords: ["menorah", "hanukkah"], category: .symbols),
        .init(glyph: "☯️", name: "Yin Yang", keywords: ["yin", "yang", "tao"], category: .symbols),
        .init(glyph: "☦️", name: "Orthodox Cross", keywords: ["cross", "orthodox"], category: .symbols),
        .init(glyph: "🛐", name: "Place of Worship", keywords: ["worship", "religion"], category: .symbols),
        .init(glyph: "⛎", name: "Ophiuchus", keywords: ["ophiuchus", "zodiac"], category: .symbols),
        .init(glyph: "♈", name: "Aries", keywords: ["aries", "zodiac"], category: .symbols),
        .init(glyph: "♉", name: "Taurus", keywords: ["taurus", "zodiac"], category: .symbols),
        .init(glyph: "♊", name: "Gemini", keywords: ["gemini", "zodiac"], category: .symbols),
        .init(glyph: "♋", name: "Cancer", keywords: ["cancer", "zodiac"], category: .symbols),
        .init(glyph: "♌", name: "Leo", keywords: ["leo", "zodiac"], category: .symbols),
        .init(glyph: "♍", name: "Virgo", keywords: ["virgo", "zodiac"], category: .symbols),
        .init(glyph: "♎", name: "Libra", keywords: ["libra", "zodiac"], category: .symbols),
        .init(glyph: "♏", name: "Scorpio", keywords: ["scorpio", "zodiac"], category: .symbols),
        .init(glyph: "♐", name: "Sagittarius", keywords: ["sagittarius", "zodiac"], category: .symbols),
        .init(glyph: "♑", name: "Capricorn", keywords: ["capricorn", "zodiac"], category: .symbols),
        .init(glyph: "♒", name: "Aquarius", keywords: ["aquarius", "zodiac"], category: .symbols),
        .init(glyph: "♓", name: "Pisces", keywords: ["pisces", "zodiac"], category: .symbols),
        .init(glyph: "🆔", name: "ID Button", keywords: ["id"], category: .symbols),
        .init(glyph: "⚛️", name: "Atom Symbol", keywords: ["atom", "science"], category: .symbols),
        .init(glyph: "🉑", name: "Japanese Acceptable Button", keywords: ["accept"], category: .symbols),
        .init(glyph: "☢️", name: "Radioactive", keywords: ["radioactive"], category: .symbols),
        .init(glyph: "☣️", name: "Biohazard", keywords: ["biohazard"], category: .symbols),
        .init(glyph: "📴", name: "Mobile Phone Off", keywords: ["phone", "off"], category: .symbols),
        .init(glyph: "📳", name: "Vibration Mode", keywords: ["phone", "vibrate"], category: .symbols),
        .init(glyph: "🈶", name: "Japanese Not Free of Charge Button", keywords: ["japanese"], category: .symbols),
        .init(glyph: "🈚", name: "Japanese Free of Charge Button", keywords: ["japanese", "free"], category: .symbols),
        .init(glyph: "🈸", name: "Japanese Application Button", keywords: ["japanese"], category: .symbols),
        .init(glyph: "🈺", name: "Japanese Open for Business Button", keywords: ["japanese", "business"], category: .symbols),
        .init(glyph: "🈷️", name: "Japanese Monthly Amount Button", keywords: ["japanese", "monthly"], category: .symbols),
        .init(glyph: "✴️", name: "Eight-Pointed Star", keywords: ["star", "eight"], category: .symbols),
        .init(glyph: "🆚", name: "VS Button", keywords: ["vs", "versus"], category: .symbols),
        .init(glyph: "🉐", name: "Japanese Bargain Button", keywords: ["japanese", "bargain"], category: .symbols),
        .init(glyph: "💠", name: "Diamond with a Dot", keywords: ["diamond", "dot"], category: .symbols),
        .init(glyph: "🔴", name: "Red Circle", keywords: ["red", "circle"], category: .symbols),
        .init(glyph: "🟠", name: "Orange Circle", keywords: ["orange", "circle"], category: .symbols),
        .init(glyph: "🟡", name: "Yellow Circle", keywords: ["yellow", "circle"], category: .symbols),
        .init(glyph: "🟢", name: "Green Circle", keywords: ["green", "circle"], category: .symbols),
        .init(glyph: "🔵", name: "Blue Circle", keywords: ["blue", "circle"], category: .symbols),
        .init(glyph: "🟣", name: "Purple Circle", keywords: ["purple", "circle"], category: .symbols),
        .init(glyph: "⚫", name: "Black Circle", keywords: ["black", "circle"], category: .symbols),
        .init(glyph: "⚪", name: "White Circle", keywords: ["white", "circle"], category: .symbols),
        .init(glyph: "🟥", name: "Red Square", keywords: ["red", "square"], category: .symbols),
        .init(glyph: "🟧", name: "Orange Square", keywords: ["orange", "square"], category: .symbols),
        .init(glyph: "🟨", name: "Yellow Square", keywords: ["yellow", "square"], category: .symbols),
        .init(glyph: "🟩", name: "Green Square", keywords: ["green", "square"], category: .symbols),
        .init(glyph: "🟦", name: "Blue Square", keywords: ["blue", "square"], category: .symbols),
        .init(glyph: "🟪", name: "Purple Square", keywords: ["purple", "square"], category: .symbols),
        .init(glyph: "⬛", name: "Black Large Square", keywords: ["black", "square"], category: .symbols),
        .init(glyph: "⬜", name: "White Large Square", keywords: ["white", "square"], category: .symbols),
        .init(glyph: "◼️", name: "Black Medium Square", keywords: ["black", "square"], category: .symbols),
        .init(glyph: "◻️", name: "White Medium Square", keywords: ["white", "square"], category: .symbols),
        .init(glyph: "◾", name: "Black Medium-Small Square", keywords: ["black", "square"], category: .symbols),
        .init(glyph: "◽", name: "White Medium-Small Square", keywords: ["white", "square"], category: .symbols),
        .init(glyph: "▪️", name: "Black Small Square", keywords: ["black", "square"], category: .symbols),
        .init(glyph: "▫️", name: "White Small Square", keywords: ["white", "square"], category: .symbols),
        .init(glyph: "🔶", name: "Large Orange Diamond", keywords: ["orange", "diamond"], category: .symbols),
        .init(glyph: "🔷", name: "Large Blue Diamond", keywords: ["blue", "diamond"], category: .symbols),
        .init(glyph: "🔸", name: "Small Orange Diamond", keywords: ["orange", "diamond"], category: .symbols),
        .init(glyph: "🔹", name: "Small Blue Diamond", keywords: ["blue", "diamond"], category: .symbols),
        .init(glyph: "🔺", name: "Red Triangle Pointed Up", keywords: ["red", "triangle", "up"], category: .symbols),
        .init(glyph: "🔻", name: "Red Triangle Pointed Down", keywords: ["red", "triangle", "down"], category: .symbols),
        .init(glyph: "➕", name: "Heavy Plus Sign", keywords: ["plus", "add", "math"], category: .symbols),
        .init(glyph: "➖", name: "Heavy Minus Sign", keywords: ["minus", "subtract", "math"], category: .symbols),
        .init(glyph: "➗", name: "Heavy Division Sign", keywords: ["divide", "math"], category: .symbols),
        .init(glyph: "✖️", name: "Heavy Multiplication X", keywords: ["multiply", "x", "math"], category: .symbols),
        .init(glyph: "🟰", name: "Heavy Equals Sign", keywords: ["equals", "math"], category: .symbols),
        .init(glyph: "♾️", name: "Infinity", keywords: ["infinity", "forever"], category: .symbols),
        .init(glyph: "‼️", name: "Double Exclamation Mark", keywords: ["exclamation"], category: .symbols),
        .init(glyph: "⁉️", name: "Exclamation Question Mark", keywords: ["exclamation", "question"], category: .symbols),
        .init(glyph: "❓", name: "Red Question Mark", keywords: ["question", "?"], category: .symbols),
        .init(glyph: "❔", name: "White Question Mark", keywords: ["question"], category: .symbols),
        .init(glyph: "❕", name: "White Exclamation Mark", keywords: ["exclamation"], category: .symbols),
        .init(glyph: "❗", name: "Red Exclamation Mark", keywords: ["exclamation", "!"], category: .symbols),
        .init(glyph: "〰️", name: "Wavy Dash", keywords: ["wavy", "dash"], category: .symbols),
        .init(glyph: "💱", name: "Currency Exchange", keywords: ["currency", "exchange"], category: .symbols),
        .init(glyph: "💲", name: "Heavy Dollar Sign", keywords: ["dollar", "money"], category: .symbols),
        .init(glyph: "⚕️", name: "Medical Symbol", keywords: ["medical", "health"], category: .symbols),
        .init(glyph: "♻️", name: "Recycling Symbol", keywords: ["recycle", "green"], category: .symbols),
        .init(glyph: "⚜️", name: "Fleur-de-Lis", keywords: ["fleur", "lis"], category: .symbols),
        .init(glyph: "🔱", name: "Trident Emblem", keywords: ["trident"], category: .symbols),
        .init(glyph: "📛", name: "Name Badge", keywords: ["name", "badge"], category: .symbols),
        .init(glyph: "🔰", name: "Japanese Symbol for Beginner", keywords: ["beginner", "japanese"], category: .symbols),
        .init(glyph: "⭕", name: "Heavy Large Circle", keywords: ["circle", "ok"], category: .symbols),
        .init(glyph: "✅", name: "Check Mark Button", keywords: ["check", "ok", "done"], category: .symbols),
        .init(glyph: "☑️", name: "Check Box with Check", keywords: ["check", "box"], category: .symbols),
        .init(glyph: "✔️", name: "Check Mark", keywords: ["check", "done"], category: .symbols),
        .init(glyph: "❌", name: "Cross Mark", keywords: ["cross", "x", "no"], category: .symbols),
        .init(glyph: "❎", name: "Cross Mark Button", keywords: ["cross", "no"], category: .symbols),
        .init(glyph: "➰", name: "Curly Loop", keywords: ["loop", "curly"], category: .symbols),
        .init(glyph: "➿", name: "Double Curly Loop", keywords: ["loop", "double"], category: .symbols),
        .init(glyph: "〽️", name: "Part Alternation Mark", keywords: ["mark"], category: .symbols),
        .init(glyph: "✳️", name: "Eight-Spoked Asterisk", keywords: ["asterisk"], category: .symbols),
        .init(glyph: "✴️", name: "Eight-Pointed Star", keywords: ["star"], category: .symbols),
        .init(glyph: "❇️", name: "Sparkle", keywords: ["sparkle"], category: .symbols),
        .init(glyph: "©️", name: "Copyright", keywords: ["copyright", "c"], category: .symbols),
        .init(glyph: "®️", name: "Registered", keywords: ["registered", "r"], category: .symbols),
        .init(glyph: "™️", name: "Trade Mark", keywords: ["trademark", "tm"], category: .symbols),
        .init(glyph: "🔃", name: "Clockwise Vertical Arrows", keywords: ["arrows", "clockwise", "loop"], category: .symbols),
        .init(glyph: "🔄", name: "Counterclockwise Arrows Button", keywords: ["arrows", "loop", "refresh"], category: .symbols),
        .init(glyph: "🔙", name: "Back Arrow", keywords: ["back", "arrow"], category: .symbols),
        .init(glyph: "🔚", name: "End Arrow", keywords: ["end", "arrow"], category: .symbols),
        .init(glyph: "🔛", name: "On Arrow", keywords: ["on", "arrow"], category: .symbols),
        .init(glyph: "🔜", name: "Soon Arrow", keywords: ["soon", "arrow"], category: .symbols),
        .init(glyph: "🔝", name: "Top Arrow", keywords: ["top", "arrow"], category: .symbols),
        .init(glyph: "🛎️", name: "Bellhop Bell", keywords: ["bell"], category: .symbols),
        .init(glyph: "🧳", name: "Luggage", keywords: ["luggage", "travel"], category: .symbols),
        .init(glyph: "🕐", name: "One OClock", keywords: ["clock", "one", "time"], category: .symbols),
        .init(glyph: "🕑", name: "Two OClock", keywords: ["clock", "two", "time"], category: .symbols),
        .init(glyph: "🕒", name: "Three OClock", keywords: ["clock", "three", "time"], category: .symbols),
        .init(glyph: "🕓", name: "Four OClock", keywords: ["clock", "four", "time"], category: .symbols),
        .init(glyph: "🕔", name: "Five OClock", keywords: ["clock", "five", "time"], category: .symbols),
        .init(glyph: "🕕", name: "Six OClock", keywords: ["clock", "six", "time"], category: .symbols),
        .init(glyph: "🕖", name: "Seven OClock", keywords: ["clock", "seven", "time"], category: .symbols),
        .init(glyph: "🕗", name: "Eight OClock", keywords: ["clock", "eight", "time"], category: .symbols),
        .init(glyph: "🕘", name: "Nine OClock", keywords: ["clock", "nine", "time"], category: .symbols),
        .init(glyph: "🕙", name: "Ten OClock", keywords: ["clock", "ten", "time"], category: .symbols),
        .init(glyph: "🕚", name: "Eleven OClock", keywords: ["clock", "eleven", "time"], category: .symbols),
        .init(glyph: "🕛", name: "Twelve OClock", keywords: ["clock", "twelve", "time"], category: .symbols),
        .init(glyph: "🕜", name: "One-Thirty", keywords: ["clock", "thirty", "time"], category: .symbols),
        .init(glyph: "🕝", name: "Two-Thirty", keywords: ["clock", "thirty", "time"], category: .symbols),
        .init(glyph: "🕞", name: "Three-Thirty", keywords: ["clock", "thirty", "time"], category: .symbols),
        .init(glyph: "🕟", name: "Four-Thirty", keywords: ["clock", "thirty", "time"], category: .symbols),
        .init(glyph: "🕠", name: "Five-Thirty", keywords: ["clock", "thirty", "time"], category: .symbols),
        .init(glyph: "🕡", name: "Six-Thirty", keywords: ["clock", "thirty", "time"], category: .symbols),
        .init(glyph: "🕢", name: "Seven-Thirty", keywords: ["clock", "thirty", "time"], category: .symbols),
        .init(glyph: "🕣", name: "Eight-Thirty", keywords: ["clock", "thirty", "time"], category: .symbols),
        .init(glyph: "🕤", name: "Nine-Thirty", keywords: ["clock", "thirty", "time"], category: .symbols),
        .init(glyph: "🕥", name: "Ten-Thirty", keywords: ["clock", "thirty", "time"], category: .symbols),
        .init(glyph: "🕦", name: "Eleven-Thirty", keywords: ["clock", "thirty", "time"], category: .symbols),
        .init(glyph: "🕧", name: "Twelve-Thirty", keywords: ["clock", "thirty", "time"], category: .symbols),

        // Flags
        .init(glyph: "🏳️", name: "White Flag", keywords: ["flag", "white"], category: .flags),
        .init(glyph: "🏴", name: "Black Flag", keywords: ["flag", "black"], category: .flags),
        .init(glyph: "🏁", name: "Chequered Flag", keywords: ["flag", "checkered", "race"], category: .flags),
        .init(glyph: "🚩", name: "Triangular Flag", keywords: ["flag", "triangular", "pin"], category: .flags),
        .init(glyph: "🏳️‍🌈", name: "Rainbow Flag", keywords: ["flag", "rainbow", "pride"], category: .flags),
        .init(glyph: "🏳️‍⚧️", name: "Transgender Flag", keywords: ["flag", "transgender"], category: .flags),
        .init(glyph: "🏴‍☠️", name: "Pirate Flag", keywords: ["flag", "pirate", "skull"], category: .flags),
        .init(glyph: "🇦🇷", name: "Argentina", keywords: ["argentina", "flag"], category: .flags),
        .init(glyph: "🇧🇷", name: "Brazil", keywords: ["brazil", "flag"], category: .flags),
        .init(glyph: "🇨🇦", name: "Canada", keywords: ["canada", "flag"], category: .flags),
        .init(glyph: "🇨🇳", name: "China", keywords: ["china", "flag"], category: .flags),
        .init(glyph: "🇫🇷", name: "France", keywords: ["france", "flag"], category: .flags),
        .init(glyph: "🇩🇪", name: "Germany", keywords: ["germany", "flag"], category: .flags),
        .init(glyph: "🇮🇳", name: "India", keywords: ["india", "flag"], category: .flags),
        .init(glyph: "🇮🇹", name: "Italy", keywords: ["italy", "flag"], category: .flags),
        .init(glyph: "🇯🇵", name: "Japan", keywords: ["japan", "flag"], category: .flags),
        .init(glyph: "🇲🇽", name: "Mexico", keywords: ["mexico", "flag"], category: .flags),
        .init(glyph: "🇷🇺", name: "Russia", keywords: ["russia", "flag"], category: .flags),
        .init(glyph: "🇪🇸", name: "Spain", keywords: ["spain", "flag"], category: .flags),
        .init(glyph: "🇬🇧", name: "United Kingdom", keywords: ["uk", "britain", "flag"], category: .flags),
        .init(glyph: "🇺🇸", name: "United States", keywords: ["usa", "us", "america", "flag"], category: .flags),
        .init(glyph: "🇦🇺", name: "Australia", keywords: ["australia", "flag"], category: .flags),
        .init(glyph: "🇧🇪", name: "Belgium", keywords: ["belgium", "flag"], category: .flags),
        .init(glyph: "🇨🇱", name: "Chile", keywords: ["chile", "flag"], category: .flags),
        .init(glyph: "🇨🇴", name: "Colombia", keywords: ["colombia", "flag"], category: .flags),
        .init(glyph: "🇩🇰", name: "Denmark", keywords: ["denmark", "flag"], category: .flags),
        .init(glyph: "🇪🇬", name: "Egypt", keywords: ["egypt", "flag"], category: .flags),
        .init(glyph: "🇬🇷", name: "Greece", keywords: ["greece", "flag"], category: .flags),
        .init(glyph: "🇭🇰", name: "Hong Kong", keywords: ["hongkong", "flag"], category: .flags),
        .init(glyph: "🇮🇪", name: "Ireland", keywords: ["ireland", "flag"], category: .flags),
        .init(glyph: "🇮🇱", name: "Israel", keywords: ["israel", "flag"], category: .flags),
        .init(glyph: "🇰🇷", name: "South Korea", keywords: ["korea", "south", "flag"], category: .flags),
        .init(glyph: "🇳🇱", name: "Netherlands", keywords: ["netherlands", "dutch", "flag"], category: .flags),
        .init(glyph: "🇳🇿", name: "New Zealand", keywords: ["newzealand", "flag"], category: .flags),
        .init(glyph: "🇳🇴", name: "Norway", keywords: ["norway", "flag"], category: .flags),
        .init(glyph: "🇵🇪", name: "Peru", keywords: ["peru", "flag"], category: .flags),
        .init(glyph: "🇵🇭", name: "Philippines", keywords: ["philippines", "flag"], category: .flags),
        .init(glyph: "🇵🇹", name: "Portugal", keywords: ["portugal", "flag"], category: .flags),
        .init(glyph: "🇸🇦", name: "Saudi Arabia", keywords: ["saudi", "arabia", "flag"], category: .flags),
        .init(glyph: "🇸🇪", name: "Sweden", keywords: ["sweden", "flag"], category: .flags),
        .init(glyph: "🇨🇭", name: "Switzerland", keywords: ["switzerland", "swiss", "flag"], category: .flags),
        .init(glyph: "🇹🇷", name: "Turkey", keywords: ["turkey", "flag"], category: .flags),
        .init(glyph: "🇺🇦", name: "Ukraine", keywords: ["ukraine", "flag"], category: .flags),
        .init(glyph: "🇻🇪", name: "Venezuela", keywords: ["venezuela", "flag"], category: .flags),
        .init(glyph: "🇿🇦", name: "South Africa", keywords: ["southafrica", "flag"], category: .flags),
        .init(glyph: "🇪🇺", name: "European Union", keywords: ["eu", "europe", "flag"], category: .flags),
        .init(glyph: "🇺🇳", name: "United Nations", keywords: ["un", "nations", "flag"], category: .flags)
    ]
}

public extension EmojiCatalog {
    /// Filter the catalog by a query. Empty query returns everything. Matching
    /// is case-insensitive against name and keywords.
    static func search(_ query: String) -> [EmojiEntry] {
        let q = query.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: nil).trimmingCharacters(in: .whitespaces)
        guard !q.isEmpty else { return entries }
        return entries.filter { entry in
            if entry.name.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: nil).contains(q) { return true }
            return entry.keywords.contains(where: { $0.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: nil).contains(q) })
        }
    }

    /// Group entries by category, preserving the `EmojiCategory` order. Empty
    /// categories are omitted so the UI has no empty sections.
    static func grouped(_ entries: [EmojiEntry]) -> [(EmojiCategory, [EmojiEntry])] {
        EmojiCategory.allCases.compactMap { category in
            let items = entries.filter { $0.category == category }
            return items.isEmpty ? nil : (category, items)
        }
    }
}
